MastersAcademy/fe-course-basic-2023

- homeworks/oleksandr.khodakivskyi_Moo0oony/README.MD
> Added README.MD -- first hometask

- homeworks/max.snischuk_snischuk/0-intro/README.md
> 0-intro_snischuk

- homeworks/roman.pavliuk_RomanPvlk/0-intro/README.MD
Reverts MastersAcademy/fe-course-basic-2023#27
> Revert "0-intro_RomanPvlk"

- homeworks/olena.ambitska_elena-ambitska/0-intro/README.md
> 0-intro elena ambitska

- homeworks/sviatoslav.taranenko_SviatoslavTaranenko/0-intro/README.MD
> Add node, npm, information about way to node

- homeworks/bogdan.yatsentiuk_Bogdandrummer/0-intro/README.MD
> 0 intro bogdandrummer

- homeworks/rostyslav.vyshemirskyi_Rooosss/0-intro/README.MD
> added README.MD

- homeworks/ekaterina.sharova_rogerosha/PokemonProject/index.html
- homeworks/ekaterina.sharova_rogerosha/PokemonProject/style.css
This pull request adds a web page showcasing my personal introduction and information, inspired by the provided Pokemon design. It's built using HTML and CSS, creating an engaging and personalized online presence.
> HW-1: Add base HTML and CSS

- homeworks/max.snischuk_snischuk/PokemonProject/index.css
- homeworks/max.snischuk_snischuk/PokemonProject/index.html
> 1-html_snischuk

- homeworks/rostyslav.vyshemirskyi_Rooosss/PokemonProject/index.html
- homeworks/rostyslav.vyshemirskyi_Rooosss/PokemonProject/style.css
A simple index.html document has been created and a style.css file with styles has been added.
> A simple index.html document has been created and a style.css file with styles has been added

- homeworks/taras.bobov_LotusElize/GamesProject/index.html
- homeworks/taras.bobov_LotusElize/GamesProject/style.css
> new file: index.html

- homeworks/david.tereshchenko_DavidTereshchenko/GameProject/css/style.css
- homeworks/david.tereshchenko_DavidTereshchenko/GameProject/game.html
- homeworks/david.tereshchenko_DavidTereshchenko/GameProject/index.html
сам список nav не робив з grid, думаю він там лишній
> header in "about" for an asterisk

- homeworks/rostyslav.vyshemirskyi_Rooosss/PokemonProject/image/check.svg
- homeworks/rostyslav.vyshemirskyi_Rooosss/PokemonProject/index.html
- homeworks/rostyslav.vyshemirskyi_Rooosss/PokemonProject/login.html
- homeworks/rostyslav.vyshemirskyi_Rooosss/PokemonProject/pokemons.html
- homeworks/rostyslav.vyshemirskyi_Rooosss/PokemonProject/style.css
- homeworks/rostyslav.vyshemirskyi_Rooosss/PokemonProject/success.html
- homeworks/rostyslav.vyshemirskyi_Rooosss/PokemonProject/sucsses.html
added page with form and page with successful login
> added page with form and page with successful login

- homeworks/artur.kobyliatsky_Allocene/4-basics/basics.js
- homeworks/artur.kobyliatsky_Allocene/4-basics/index.html
- homeworks/artur.kobyliatsky_Allocene/4-basics/style.css
added new folder: 4-basics
added files: index, style, js
do some magic with basic logic
> 4-js_basics_Allocene

- homeworks/rostyslav.vyshemirskyi_Rooosss/4-basics/basics.js
- homeworks/rostyslav.vyshemirskyi_Rooosss/4-basics/index.html
- homeworks/rostyslav.vyshemirskyi_Rooosss/PokemonProject/style.css
created index.html and basics.js file and added basic math operations in javaScript
> created index.html and basics.js file and added basic math operations in javaScript

- homeworks/olena.ambitska_elena-ambitska/4-basics/basics.js
- homeworks/olena.ambitska_elena-ambitska/4-basics/index.html
- homeworks/olena.ambitska_elena-ambitska/4-basics/styles.css
- homeworks/olena.ambitska_elena-ambitska/GamesProject/success.html
- fixed button from HW-3
- added basic math operations 
<details>
</details>
> 4-js_basics elena-ambitska

- homeworks/roman.lytvynenko_Lytvynenko18/GamesProject/Style/login.css
- homeworks/roman.lytvynenko_Lytvynenko18/GamesProject/Style/style.css
- homeworks/roman.lytvynenko_Lytvynenko18/GamesProject/games.html
- homeworks/roman.lytvynenko_Lytvynenko18/GamesProject/index.html
- homeworks/roman.lytvynenko_Lytvynenko18/GamesProject/login.html
- homeworks/roman.lytvynenko_Lytvynenko18/GamesProject/success.html
home_work_3-forms
added pages: Login, "Success"
2aa8191896cb96ccc6b04e19dad11cf5661541c7
> home_work3_Login_page

- homeworks/oleksandr.khodakivskyi_Moo0oony/4-basics/basics.js
- homeworks/oleksandr.khodakivskyi_Moo0oony/4-basics/index.html
- homeworks/oleksandr.khodakivskyi_Moo0oony/4-basics/style.css
Completed the main and the additional tasks -- the results can be seen in the console and on the page
> 4-js_basics

- homeworks/taras.bobov_LotusElize/GamesProject/css/games.css
- homeworks/taras.bobov_LotusElize/GamesProject/css/login.css
- homeworks/taras.bobov_LotusElize/GamesProject/css/style.css
- homeworks/taras.bobov_LotusElize/GamesProject/css/success.css
- homeworks/taras.bobov_LotusElize/GamesProject/games.html
- homeworks/taras.bobov_LotusElize/GamesProject/index.html
- homeworks/taras.bobov_LotusElize/GamesProject/login.html
- homeworks/taras.bobov_LotusElize/GamesProject/success.html
Created a login page with a form, implemented email field validation, concealed the password, added focus on label click, and created a success login page with a 'Return to homepage' button for redirection
> Сreated login page, success login page.

- homeworks/vladyslav.brusentsov_vBrusentsov/GamesProject/Img/arrow.svg
- homeworks/vladyslav.brusentsov_vBrusentsov/GamesProject/Img/filter-checkbox.svg
- homeworks/vladyslav.brusentsov_vBrusentsov/GamesProject/Img/login-checkbox.svg
- homeworks/vladyslav.brusentsov_vBrusentsov/GamesProject/Img/search-bar-logo.svg
- homeworks/vladyslav.brusentsov_vBrusentsov/GamesProject/css/aboutStyle.css
- homeworks/vladyslav.brusentsov_vBrusentsov/GamesProject/css/gamesStyle.css
- homeworks/vladyslav.brusentsov_vBrusentsov/GamesProject/css/login.css
- homeworks/vladyslav.brusentsov_vBrusentsov/GamesProject/css/main.css
- homeworks/vladyslav.brusentsov_vBrusentsov/GamesProject/css/successfulLogin.css
- homeworks/vladyslav.brusentsov_vBrusentsov/GamesProject/games.html
- homeworks/vladyslav.brusentsov_vBrusentsov/GamesProject/index.html
- homeworks/vladyslav.brusentsov_vBrusentsov/GamesProject/login.html
- homeworks/vladyslav.brusentsov_vBrusentsov/GamesProject/successfulLogin.html
> 3 forms v brusentsov

- homeworks/yehor.honcharenko_NOcode-developer/4-basics/basics.css
- homeworks/yehor.honcharenko_NOcode-developer/4-basics/basics.js
- homeworks/yehor.honcharenko_NOcode-developer/4-basics/index.html
1. Created folder "4-basics" 1.1 basic.js
1.2 index.html
1.3 basic.css
2. Created some basic math operation in .js
3. Connected .js and .css to the html
4. Displaying data through the console
> hw4-- basics, mathematics

- homeworks/yana.dankova_YanaDankova/4-basics/basics.js
- homeworks/yana.dankova_YanaDankova/4-basics/index.html
- homeworks/yana.dankova_YanaDankova/4-basics/style.css
Добрий день) в мене є сумніви чи все вірно я зрозуміла.
> 4 js basics yana dankova

- homeworks/ihor.zapisochniy_IgorFromUA/4-basics/basics.js
- homeworks/ihor.zapisochniy_IgorFromUA/4-basics/index.html
- homeworks/ihor.zapisochniy_IgorFromUA/4-basics/styles.css
implemented arithmetic operations, added operation results to the web page and styled it
> HW-4 js basics by IgorFromUA

- homeworks/roman.lytvynenko_Lytvynenko18/4-basics/basics.js
- homeworks/roman.lytvynenko_Lytvynenko18/4-basics/index.html
- homeworks/roman.lytvynenko_Lytvynenko18/4-basics/style.css
- homeworks/roman.lytvynenko_Lytvynenko18/GamesProject/login.html
a bit late, but I faced with 2 issues and spent a lot of time to findout what's wrong:
1. CRLF
2. Had trouble whith correct understandin of the task - somehow I diceded that needed to be done input filds and button to get data for js operations. Finaly I decided to reread the conditions and understood my mistake.
> home_work4

- homeworks/artur.kobyliatsky_Allocene/5-logic/homework.js
- homeworks/artur.kobyliatsky_Allocene/5-logic/index.html
- homeworks/artur.kobyliatsky_Allocene/5-logic/script.js
- homeworks/artur.kobyliatsky_Allocene/GamesProject/calculator.html
- homeworks/artur.kobyliatsky_Allocene/GamesProject/games.html
- homeworks/artur.kobyliatsky_Allocene/GamesProject/login.html
- homeworks/artur.kobyliatsky_Allocene/GamesProject/script/calculator.js
- homeworks/artur.kobyliatsky_Allocene/GamesProject/script/script.js
- homeworks/artur.kobyliatsky_Allocene/GamesProject/style/main-calculator.css
- homeworks/artur.kobyliatsky_Allocene/GamesProject/style/main-login.css
added files, realized js logic + style (Task without star)
a bit fixed mainLogin for previous homework
> 5-js_logic_Allocene

- homeworks/evgeny.tolchinsky_ryvik13/JS-basic/basic.js
- homeworks/evgeny.tolchinsky_ryvik13/JS-basic/index.css
- homeworks/evgeny.tolchinsky_ryvik13/JS-basic/index.html
Please review homework, I understand that its out of time
> 5th homework

- homeworks/rostyslav.vyshemirskyi_Rooosss/5-logic/homework.js
- homeworks/rostyslav.vyshemirskyi_Rooosss/5-logic/index.html
- homeworks/rostyslav.vyshemirskyi_Rooosss/5-logic/script.js
- homeworks/rostyslav.vyshemirskyi_Rooosss/PokemonProject/style.css
A simple calculator with the styles of your project has been created
> A simple calculator with the styles of your project has been created

- homeworks/kostiantyn.nosatskyi_NosatskyiK/4-js_basics/basics.js
- homeworks/kostiantyn.nosatskyi_NosatskyiK/4-js_basics/index.html
- homeworks/kostiantyn.nosatskyi_NosatskyiK/4-js_basics/style.css
created a new pr because the old one that was created on Sunday had conflicts that he could not fix, and created a new branch
> 4-basics_js-creation of a new branch and a new PR

- homeworks/ihor.zapisochniy_IgorFromUA/5-logic/homework.js
- homeworks/ihor.zapisochniy_IgorFromUA/5-logic/index.html
- homeworks/ihor.zapisochniy_IgorFromUA/5-logic/script.js
- homeworks/ihor.zapisochniy_IgorFromUA/5-logic/styles.css
- homeworks/ihor.zapisochniy_IgorFromUA/GamesProject/calculator.html
- homeworks/ihor.zapisochniy_IgorFromUA/GamesProject/games.html
- homeworks/ihor.zapisochniy_IgorFromUA/GamesProject/login.html
- homeworks/ihor.zapisochniy_IgorFromUA/GamesProject/scripts/homework.js
- homeworks/ihor.zapisochniy_IgorFromUA/GamesProject/scripts/script.js
- homeworks/ihor.zapisochniy_IgorFromUA/GamesProject/styles/calculator.css
- homeworks/ihor.zapisochniy_IgorFromUA/GamesProject/styles/header.css
added all the functionality as in the technical task
> HW-5 js logic by IgoFromUA

- homeworks/yehor.honcharenko_NOcode-developer/GamesProject/calculator.html
- homeworks/yehor.honcharenko_NOcode-developer/GamesProject/calculator.js
- homeworks/yehor.honcharenko_NOcode-developer/GamesProject/cards.html
- homeworks/yehor.honcharenko_NOcode-developer/GamesProject/header.js
- homeworks/yehor.honcharenko_NOcode-developer/GamesProject/login.html
- homeworks/yehor.honcharenko_NOcode-developer/GamesProject/style/about.css
- homeworks/yehor.honcharenko_NOcode-developer/GamesProject/style/calculator.css
- homeworks/yehor.honcharenko_NOcode-developer/GamesProject/style/cards.css
- homeworks/yehor.honcharenko_NOcode-developer/GamesProject/style/footer.css
- homeworks/yehor.honcharenko_NOcode-developer/GamesProject/style/header.css
- homeworks/yehor.honcharenko_NOcode-developer/GamesProject/style/login.css
1. reorganized project files
2. added calculator.html
3. added calculator.css
4. added calculator.js
5. added basic calculator
6. tryed-- calculator with advanced functionality
> hw5-- calculator with advanced functionality

- homeworks/vladyslav.brusentsov_vBrusentsov/5-logic/homework.js
- homeworks/vladyslav.brusentsov_vBrusentsov/5-logic/index.html
- homeworks/vladyslav.brusentsov_vBrusentsov/5-logic/script.js
- homeworks/vladyslav.brusentsov_vBrusentsov/GamesProject/Img/selector-calc-arrow.svg
- homeworks/vladyslav.brusentsov_vBrusentsov/GamesProject/calculator.html
- homeworks/vladyslav.brusentsov_vBrusentsov/GamesProject/css/calculator.css
- homeworks/vladyslav.brusentsov_vBrusentsov/GamesProject/css/gamesStyle.css
- homeworks/vladyslav.brusentsov_vBrusentsov/GamesProject/games.html
- homeworks/vladyslav.brusentsov_vBrusentsov/GamesProject/index.html
- homeworks/vladyslav.brusentsov_vBrusentsov/GamesProject/login.html
- homeworks/vladyslav.brusentsov_vBrusentsov/GamesProject/script/calculator.js
- homeworks/vladyslav.brusentsov_vBrusentsov/GamesProject/script/script.js
- homeworks/vladyslav.brusentsov_vBrusentsov/GamesProject/successfulLogin.html
Ended task with star but without use pictures
> 5 js logic v brusentsov

- homeworks/taras.bobov_LotusElize/5-logic/homework.js
- homeworks/taras.bobov_LotusElize/5-logic/img/arrow.svg
- homeworks/taras.bobov_LotusElize/5-logic/index.html
- homeworks/taras.bobov_LotusElize/5-logic/script.js
- homeworks/taras.bobov_LotusElize/5-logic/style.css
Add calculator logic to 5-logic project, including error handling for invalid inputs and results
> Add calculator logic to 5-logic project.

- homeworks/david.tereshchenko_DavidTereshchenko/5-logic/homework.js
- homeworks/david.tereshchenko_DavidTereshchenko/5-logic/index.html
- homeworks/david.tereshchenko_DavidTereshchenko/5-logic/style.css
I adapted the previous homework, I will do it a little later with an asterisk)
> added 5-logic

- homeworks/ekaterina.sharova_rogerosha/5-logic/homework.js
- homeworks/ekaterina.sharova_rogerosha/5-logic/index.html
- homeworks/ekaterina.sharova_rogerosha/5-logic/script.js
- homeworks/ekaterina.sharova_rogerosha/5-logic/style.css
- homeworks/ekaterina.sharova_rogerosha/PokemonProject/css/login.css
- homeworks/ekaterina.sharova_rogerosha/PokemonProject/css/pokemons.css
- homeworks/ekaterina.sharova_rogerosha/PokemonProject/index.html
- homeworks/ekaterina.sharova_rogerosha/PokemonProject/login.html
- homeworks/ekaterina.sharova_rogerosha/PokemonProject/pokemons.html
Hello! I set the calculator to the fifth homework, it works as it must:
Also, if I would choose '%' or '**', the function will return error:
And if the result is smaller than 0 or bigger than 100, the function will return error as well:
Thanks for the review! 🌷
> HW-5: Add JS logic

- homeworks/artur.kobyliatsky_Allocene/GamesProject/login.html
- homeworks/artur.kobyliatsky_Allocene/GamesProject/script/validate.js
- homeworks/artur.kobyliatsky_Allocene/GamesProject/style/main-login.css
Added validate logic to page login.html + styles
> 6-functions_Allocene

- homeworks/rostyslav.vyshemirskyi_Rooosss/PokemonProject/login.html
- homeworks/rostyslav.vyshemirskyi_Rooosss/PokemonProject/scripts/script.js
- homeworks/rostyslav.vyshemirskyi_Rooosss/PokemonProject/style.css
Added registration form validation
> Added registration form validation

- homeworks/ihor.zapisochniy_IgorFromUA/5-logic/homework.js
- homeworks/ihor.zapisochniy_IgorFromUA/GamesProject/login.html
- homeworks/ihor.zapisochniy_IgorFromUA/GamesProject/scripts/homework.js
- homeworks/ihor.zapisochniy_IgorFromUA/GamesProject/scripts/script-login.js
- homeworks/ihor.zapisochniy_IgorFromUA/GamesProject/scripts/script.js
- homeworks/ihor.zapisochniy_IgorFromUA/GamesProject/styles/login.css
completed the task with an asterisk. and fixed the 5th homework
> HW-6 functions by IgorFromUA

- homeworks/vladyslav.brusentsov_vBrusentsov/GamesProject/css/login.css
- homeworks/vladyslav.brusentsov_vBrusentsov/GamesProject/index.html
- homeworks/vladyslav.brusentsov_vBrusentsov/GamesProject/login.html
- homeworks/vladyslav.brusentsov_vBrusentsov/GamesProject/script/logining-veryfication-script.js
> 6 functions v brusentsov

- homeworks/ihor.zapisochniy_IgorFromUA/7-arrays-loops/arrays.js
completed the main task and the task with an asterisk.
> HW-7 arrays, methods of arrays and loops by IgorFromUA.

- homeworks/rostyslav.vyshemirskyi_Rooosss/7-arrays-loops/arrays.js
added functions to calculate arrays
> added functions to calculate arrays

- homeworks/rostyslav.vyshemirskyi_Rooosss/PokemonProject/calculator.html
- homeworks/rostyslav.vyshemirskyi_Rooosss/PokemonProject/index.html
- homeworks/rostyslav.vyshemirskyi_Rooosss/PokemonProject/pokemons.html
- homeworks/rostyslav.vyshemirskyi_Rooosss/PokemonProject/scripts/calculator.js
- homeworks/rostyslav.vyshemirskyi_Rooosss/PokemonProject/scripts/default.js
- homeworks/rostyslav.vyshemirskyi_Rooosss/PokemonProject/success.html
added a calculator to my project
> added a calculator to my project

- homeworks/andrii.morozov_AndriiMorozov88/GamesProject/calculator.html
- homeworks/andrii.morozov_AndriiMorozov88/GamesProject/scripts/logic.js
- homeworks/andrii.morozov_AndriiMorozov88/GamesProject/styles/calculator.css
> 6 functions andrii morozov88

- homeworks/oleksandr.khodakivskyi_Moo0oony/7-array-loops/arrays.js
Completed the main and additional tasks
> 7-array-loops

- homeworks/artur.kobyliatsky_Allocene/7-arrays-loops/arrays.js
added main homework + task with "*" also I committed all code because linter doesn't want to skip code
> 7-arrays_loops_Allocene

- homeworks/artur.kobyliatsky_Allocene/GamesProject/calculator.html
- homeworks/artur.kobyliatsky_Allocene/GamesProject/script/calculator.js
- homeworks/artur.kobyliatsky_Allocene/GamesProject/style/main-calculator.css
- homeworks/artur.kobyliatsky_Allocene/GamesProject/style/main-games.css
add time duration + function execution + task with " * "
> 7-js_strings_dates_Allocene

- homeworks/olena.ambitska_elena-ambitska/GamesProject/calc.html
- homeworks/olena.ambitska_elena-ambitska/GamesProject/cards.html
- homeworks/olena.ambitska_elena-ambitska/GamesProject/index.html
- homeworks/olena.ambitska_elena-ambitska/GamesProject/login.html
- homeworks/olena.ambitska_elena-ambitska/GamesProject/scripts/homework.js
- homeworks/olena.ambitska_elena-ambitska/GamesProject/scripts/script.js
- homeworks/olena.ambitska_elena-ambitska/GamesProject/styles/counter-styles.css
Added additional description, date, and performance time
> 7-js_strings_dates-elena-ambitska

- homeworks/ihor.zapisochniy_IgorFromUA/GamesProject/calculator.html
- homeworks/ihor.zapisochniy_IgorFromUA/GamesProject/scripts/homework.js
- homeworks/ihor.zapisochniy_IgorFromUA/GamesProject/scripts/script.js
- homeworks/ihor.zapisochniy_IgorFromUA/GamesProject/styles/calculator.css
added the note game/games to the result and added text with the date and time the function was executed.
> HW-7 js strings dates by IgorFromUA

- homeworks/ekaterina.sharova_rogerosha/PokemonProject/css/login.css
- homeworks/ekaterina.sharova_rogerosha/PokemonProject/login.html
- homeworks/ekaterina.sharova_rogerosha/PokemonProject/scripts/script.js
Hello! 
I added all the functions to script.js file and did extra task:
or 
Thanks for the review 🌷
> HW-6: Add JS functions

- homeworks/yehor.honcharenko_NOcode-developer/7-arrays-loops/arrays.js
- homeworks/yehor.honcharenko_NOcode-developer/GamesProject/calculator.html
- homeworks/yehor.honcharenko_NOcode-developer/GamesProject/scripts/calculator.js
1. Updated Calculator Functionality: Enhanced the calculator function to append the word "game" or "games" to the result based on the calculated value. If the result is 1, "game" is appended. If the result is greater than 1, "games" is appended.
2. Added Execution Time Display: Implemented a feature to display the date and time of calculation, as well as the execution time of the function in milliseconds. The date is displayed in the format "16-Nov-2023, 17:30".
3. Updated JSDoc: Updated the JSDoc for the calculate function to reflect the new return type (string) and the appended words to the result.
4. Fixed Linter Errors: Resolved linter errors related to undefined variables and parentheses around arrow function arguments.
5. CSS Adjustments: Made some adjustments to the CSS for better …
> hw 7 + 7.5 Arrays, Methods of Arrays, Loops, Strings, Dates

- homeworks/ekaterina.sharova_rogerosha/7-arrays-loops/arrays.js
Hello! I did the task and added comments to every action to be more comfortable to navigate:
Thanks for the review! 🌷
> HW-7:  Add array functions

- homeworks/vladyslav.brusentsov_vBrusentsov/GamesProject/calculator.html
- homeworks/vladyslav.brusentsov_vBrusentsov/GamesProject/css/calculator.css
- homeworks/vladyslav.brusentsov_vBrusentsov/GamesProject/script/calculator.js
- homeworks/vladyslav.brusentsov_vBrusentsov/GamesProject/script/script.js
> 7 js strings dates v brusentsov

- homeworks/roman.lytvynenko_Lytvynenko18/GamesProject/Scripts/script.js
- homeworks/roman.lytvynenko_Lytvynenko18/GamesProject/Style/login.css
- homeworks/roman.lytvynenko_Lytvynenko18/GamesProject/login.html
It's my first time with js functions, so it took a lot of time to find out how it works.
Pls reveiw.
> home_work6

- homeworks/roman.lytvynenko_Lytvynenko18/7-arrays-loops/arrays.js
Hey, Vlad.
I know that I broke the deadlines and it’s up to U to check it or not.
The reason of that is crazy action in the work projects I involved in. It was every day some tasks with "yesterday" deadline, so I worked with no weekends. It was something like - "He had no life".
I didn't ask about moving deadline because of thought "tomorrow I can do that". And tomorrow i got new task...
I will be appreciated if you find some time to check my homework.
> home_work7

- homeworks/rostyslav.vyshemirskyi_Rooosss/PokemonProject/calculator.html
- homeworks/rostyslav.vyshemirskyi_Rooosss/PokemonProject/image/arrow.svg
- homeworks/rostyslav.vyshemirskyi_Rooosss/PokemonProject/image/check-filters.svg
- homeworks/rostyslav.vyshemirskyi_Rooosss/PokemonProject/image/search-icon.svg
- homeworks/rostyslav.vyshemirskyi_Rooosss/PokemonProject/pokemons.html
- homeworks/rostyslav.vyshemirskyi_Rooosss/PokemonProject/scripts/calculator.js
- homeworks/rostyslav.vyshemirskyi_Rooosss/PokemonProject/scripts/pokemons.js
- homeworks/rostyslav.vyshemirskyi_Rooosss/PokemonProject/style.css
added pokemon cards using javascript
> added pokemon cards using javascript

- homeworks/ekaterina.sharova_rogerosha/PokemonProject/css/pokemons.css
- homeworks/ekaterina.sharova_rogerosha/PokemonProject/pokemons.html
- homeworks/ekaterina.sharova_rogerosha/PokemonProject/scripts/pokemons.js
Hello!
I made the homework using DOM: rewrote part of HTML code for cards and added the sorting of pokemons:
Sorry for the delay! Thanks for the review! 🌷
> HW-8: DOM events

- homeworks/vladyslav.brusentsov_vBrusentsov/GamesProject/css/gamesStyle.css
- homeworks/vladyslav.brusentsov_vBrusentsov/GamesProject/css/main.css
- homeworks/vladyslav.brusentsov_vBrusentsov/GamesProject/games.html
- homeworks/vladyslav.brusentsov_vBrusentsov/GamesProject/script/games.js
End task with star
I commented from 286 to 288 rows because I had a problem with stylelint " value-no-vendor-prefix"
> 8 dom v brusentsov

- homeworks/kostiantyn.nosatskyi_NosatskyiK/PokemonProject/calculator.css
- homeworks/kostiantyn.nosatskyi_NosatskyiK/PokemonProject/calculator.html
- homeworks/kostiantyn.nosatskyi_NosatskyiK/PokemonProject/index.html
- homeworks/kostiantyn.nosatskyi_NosatskyiK/PokemonProject/js/homework.js
- homeworks/kostiantyn.nosatskyi_NosatskyiK/PokemonProject/js/login.js
- homeworks/kostiantyn.nosatskyi_NosatskyiK/PokemonProject/js/pokemon.js
- homeworks/kostiantyn.nosatskyi_NosatskyiK/PokemonProject/js/script.js
- homeworks/kostiantyn.nosatskyi_NosatskyiK/PokemonProject/login.css
- homeworks/kostiantyn.nosatskyi_NosatskyiK/PokemonProject/login.html
- homeworks/kostiantyn.nosatskyi_NosatskyiK/PokemonProject/pokemons.css
- homeworks/kostiantyn.nosatskyi_NosatskyiK/PokemonProject/pokemons.html
- homeworks/kostiantyn.nosatskyi_NosatskyiK/PokemonProject/style.css
- homeworks/kostiantyn.nosatskyi_NosatskyiK/PokemonProject/successful.html
Додав всі файли в одну папку PokemonProject, а старий pull request закрив
> 8 dom NosatskyiK

- homeworks/yehor.honcharenko_NOcode-developer/GamesProject/cards.html
- homeworks/yehor.honcharenko_NOcode-developer/GamesProject/scripts/games.js
- homeworks/yehor.honcharenko_NOcode-developer/GamesProject/style/cards.css
1. New functionality (logic) was created
2. Parsing data from the API
3. Sliced cards (50max)
3. Added loader
> hw9-- Async & Fetch

- homeworks/rostyslav.vyshemirskyi_Rooosss/PokemonProject/pokemons.html
- homeworks/rostyslav.vyshemirskyi_Rooosss/PokemonProject/scripts/pokemons.js
- homeworks/rostyslav.vyshemirskyi_Rooosss/PokemonProject/style.css
added the function of loading cards via api
> added the function of loading cards via api

- homeworks/david.tereshchenko_DavidTereshchenko/GameProject/css/game.css
- homeworks/david.tereshchenko_DavidTereshchenko/GameProject/game.html
- homeworks/david.tereshchenko_DavidTereshchenko/GameProject/script/cards.js
- lectures/7-5-string/string.js
tomorrow I will try to make an asterisk)
> 8 dom  david tereshchenko

- homeworks/vladyslav.brusentsov_vBrusentsov/GamesProject/css/gamesStyle.css
- homeworks/vladyslav.brusentsov_vBrusentsov/GamesProject/games.html
- homeworks/vladyslav.brusentsov_vBrusentsov/GamesProject/script/games.js
> 9 async vBbrusentsov

- docs/index.html
- docs/src/js/cards.js
- docs/src/js/developers.js
- docs/src/styles/card.css
- docs/src/styles/style.css
1. Removed general page styles from the card.css file
2. Removed the connection line of the card.css file from the main index.html and connected it using import in the style.css file
> code optimization

- docs/index.html
- docs/src/js/developers.js
Added link on social networks and teg target
I also added a comma in line 6 of the developer.js file, because otherwise Eslinter did not skip it
> added link on social networks and teg target

- docs/src/js/developers.js
> added social link
